//
// Created by root on 2/16/19.
//

#ifndef LINUX_C_EXERCISECODE_ASY_CLEAN_CHILD_PROCESS_H
#define LINUX_C_EXERCISECODE_ASY_CLEAN_CHILD_PROCESS_H
void my_asycleanchildprocess_main();
#endif //LINUX_C_EXERCISECODE_ASY_CLEAN_CHILD_PROCESS_H
